### ISSUE TITLE
Bug: types safety does not work when using instance.createUser()

### ISSUE THREAD

**Issue by N0SAFE** [linefusion/indirectus#9]
### Description of the bug

when using the instance created by createTypesClient the function createUser does not have the same type safety as if i do DirectusSDKcreateUser()

type collections = {
    directus_users: {
        namteste: Types.Optional<Types.String>
    }[]
}

const directus = createTypedClient('http://localhost:8055')

directus.createUser({
    test: 'test', <- error: Object literal may only specify known properties, and 'test' does not exist in type X
})

directus.request(
    DirectusSDK.createUser({
        test: 'test', <- no error
    })
)

### Steps To Reproduce

1. create a new field inside the collection user like test: string
2. generate the client.ts
3. use the createTypedClient to generate a new instanceOfDirectus with the custom function
4. use the function instance.createUser and see that the property test is not infered as a property required in createUser
5. however: when using the request cunction i have the infered type (directus.request(DirectusDSK.createUser({test: 'test'}))<- no error)

**Comment by WoLfulus** [comment]
Fixed in the next release

![image](https://github.com/user-attachments/assets/d7385a56-9982-48cf-a860-20b29aac0b7e)

**Comment by WoLfulus** [comment]
Side note: there's still some cases where the schema type injection will fail, and to automate that part I'll have to add a good chunk of code to the generation engine, which I can't do right now. I'll keep this in mind whenever I have more time to deal with this, for now cases where it fails (like .aggregate), just use .request(aggregate()) instead.

And to be honest, even the SDK itself doesn't handle those types properly, like Partial<T> for creation doesn't make sense at all (required fields are a type mismatch in this case). Would love to support something like Create<T> instead and replace the whole thing instead of proxying types from the SDK.
